FortranParameterList_Example – FPL
FortranParameterList_Example Program
70 statements
Source File
Uses:
FPL
iso_fortran_env
Example based on Teuchos::ParameterList documentation
Setting parameters in My_List Create a 'Preconditioner' SubList of parameters Setting parameters in Prec_List Has a solver been chosen Has a preconditioner been chosen Has tolerance been chosen and is of the expected data type Get method thtat retrieves a parameter of a particular type
Calls
Variables
My_List My_List_Iterator Prec_List Prec_List_Iterator FPLError solver_defined prec_defined has_same_type Tolerance String
Variables
Type Attributes Name Initial
type(ParameterList_t) :: My_List
type(ParameterListIterator_t) :: My_List_Iterator
type(ParameterList_t), pointer :: Prec_List
type(ParameterListIterator_t) :: Prec_List_Iterator
integer :: FPLError
logical :: solver_defined
logical :: prec_defined
logical :: has_same_type
real(kind=REAL64) :: Tolerance
character(len=:), allocatable :: String
All Programs
compact_real FortranParameterList_Example main ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test test_all WrapperFactoryList_I1P_Test WrapperFactoryList_I2P_Test WrapperFactoryList_I4P_Test WrapperFactoryList_I8P_Test WrapperFactoryList_R4P_Test WrapperFactoryList_R8P_Test WrapperFactoryList_Test WrapperTheWrapperFactoryList_Test
Call graph
fortranparameterlist_example calls fpl_finalize, fpl_init
fpl_init calls thewrapperfactorylist_init