main – FPL
main Program
31 statements
Source File
Uses:
FPL
Circle
CircleWrapperFactory
iso_fortran_env
Add the new WrapperFactory to the list of factories Sets the default size of the Dictionary Add parameters to the list Add a SubList to the list Add parameters to the Cicles SubList Print the content of MyList (Recursive) Free MyList Finalize FPL and free TheWrapperFactoryList
Calls
Variables
MyCircle MyList CircleList FPLError String
Variables
Type Attributes Name Initial
type(Circle_t) :: MyCircle
type(ParameterList_t) :: MyList
type(ParameterList_t), pointer :: CircleList
integer :: FPLError
character(len=:), allocatable :: String
Initialize FPL with the default WrapperFactories
All Programs
compact_real FortranParameterList_Example main ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test ParameterListEntryContainer_Test test_all WrapperFactoryList_I1P_Test WrapperFactoryList_I2P_Test WrapperFactoryList_I4P_Test WrapperFactoryList_I8P_Test WrapperFactoryList_R4P_Test WrapperFactoryList_R8P_Test WrapperFactoryList_Test WrapperTheWrapperFactoryList_Test
Call graph
main calls fpl_finalize, fpl_init
fpl_init calls thewrapperfactorylist_init