FPL_Finalize – FPL
FPL_Finalize Subroutine
3 statements
Source File
public subroutine FPL_Finalize()
Finalize FPL
Arguments
None
Called By
Source Code
FPL_Finalize
Source Code
    subroutine FPL_Finalize()
    !-----------------------------------------------------------------
    !< Finalize FPL
    !-----------------------------------------------------------------
        call TheWrapperFactoryList%Free()
    end subroutine FPL_Finalize
All Procedures
byte_size_logical FPL_Finalize FPL_Init TheWrapperFactoryList_Init
Call graph
fortranparameterlist_example calls fpl_finalize
parameterlistentrycontainer_test calls fpl_finalize
main calls fpl_finalize