TheWrapperFactoryList_Init – FPL
TheWrapperFactoryList_Init Subroutine
10 statements
Source File
public subroutine TheWrapperFactoryList_Init()
Set the dimensions of the Value contained in the wrapper
Arguments
None
Called By
Source Code
TheWrapperFactoryList_Init
Source Code
    subroutine TheWrapperFactoryList_Init()
    !-----------------------------------------------------------------
    !< Set the dimensions of the Value contained in the wrapper
    !-----------------------------------------------------------------
        ! Add some Wrapper Factories to the list
        call TheWrapperFactoryList%AddWrapperFactory(key='I1P',  WrapperFactory=WrapperFactoryI1P)
        call TheWrapperFactoryList%AddWrapperFactory(key='I2P',  WrapperFactory=WrapperFactoryI2P)
        call TheWrapperFactoryList%AddWrapperFactory(key='I4P',  WrapperFactory=WrapperFactoryI4P)
        call TheWrapperFactoryList%AddWrapperFactory(key='I8P',  WrapperFactory=WrapperFactoryI8P)
        call TheWrapperFactoryList%AddWrapperFactory(key='R4P',  WrapperFactory=WrapperFactoryR4P)
        call TheWrapperFactoryList%AddWrapperFactory(key='R8P',  WrapperFactory=WrapperFactoryR8P)
        call TheWrapperFactoryList%AddWrapperFactory(key='L',    WrapperFactory=WrapperFactoryL)
        call TheWrapperFactoryList%AddWrapperFactory(key='DLCA', WrapperFactory=WrapperFactoryDLCA)
    end subroutine TheWrapperFactoryList_Init
All Procedures
bcton bit_size bstr byte_size byte_size_logical cton FPL_Finalize FPL_Init str strz TheWrapperFactoryList_Init
Call graph
wrapperthewrapperfactorylist_test calls thewrapperfactorylist_init
wrapperfactorylist_i2p_test calls thewrapperfactorylist_init
wrapperfactorylist_r4p_test calls thewrapperfactorylist_init
fpl_init calls thewrapperfactorylist_init
wrapperfactorylist_i8p_test calls thewrapperfactorylist_init
wrapperfactorylist_i4p_test calls thewrapperfactorylist_init
wrapperfactorylist_i1p_test calls thewrapperfactorylist_init
wrapperfactorylist_test calls thewrapperfactorylist_init
wrapperfactorylist_r8p_test calls thewrapperfactorylist_init
parameterlistentrycontainer_test calls fpl_init
fortranparameterlist_example calls fpl_init
main calls fpl_init